FROM codeberg.org/forgejo/forgejo:16.0.5-rootless@sha256:5effb7305584aca479b29fde6f9631a6dbe86ae798ae02eeea33a3666f0c0bf8
COPY --chmod=755 containers/forgejo-init.sh /usr/local/bin/lab-forgejo-init
CMD ["/usr/local/bin/lab-forgejo-init"]
